owner: FourthEstateOrg
repo: status.fourthestate.org

sites:
  - name: Fourth Estate® Website
    url: https://www.fourthestate.org
  - name: Fourth Estate® Newsroom 
    url: https://newsroom.fourthestate.org
  - name: Fourth Estate® NewsHub 
    url: https://newshub.fourthestate.org
  - name: Fourth Estate® DailyNewsBrief 
    url: https://dailynewsbrief.com
  - name: Fourth Estate® Shop
    url: https://shop.fourthestate.org/
  - name: Help Desk
    url: https://helpdesk.fourthestate.org
  - name: Job Site
    url: https://jobs.fourthestate.org
  - name: Calendar
    url: https://calendar.fourthestate.org/
  - name: Mail Servers
    url: https://mail.fourthestate.org/
  - name: Ceriph™ [matrix]
    url: https://app.fourthestate.chat/

status-website:
  cname: status.fourthestate.org
  logoUrl: https://raw.githubusercontent.com/FourthEstateOrg/status.fourthestate.org/master/assets/FE_logo_glyph_color.svg
  favicon: https://raw.githubusercontent.com/FourthEstateOrg/status.fourthestate.org/master/assets/FE_logo_glyph_color.png
  faviconSvg: https://raw.githubusercontent.com/FourthEstateOrg/status.fourthestate.org/master/assets/FE_logo_glyph_color.svg
  name: System Status
  navbar:
    - title: Status
      href: /
    - title: Help Desk
      href: https://helpdesk.fourthestate.org
    - title: Fourth Estate®
      href: https://www.fourthestate.org
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

assignees:
  - FourthEstateSupport

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
