# Change these first
owner: FourthEstateOrg # Your GitHub organization or username, where this repository lives
repo: status.fourthestate.org # The name of this repository

sites:
  - name: Fourth Estate
    url: https://www.fourthestate.org
  - name: Fourth Estate® Newsroom 
    url: https://newsroom.fourthestate.org
  - name: Fourth Estate® NewsHub 
    url: https://newshub.fourthestate.org
  - name: Fourth Estate® DailyNewsBrief 
    url: https://dailynewsbrief.com
  - name: Help Desk
    url: https://helpdesk.fourthestate.org
  - name: Job Site
    url: https://jobs.fourthestate.org
   - name: Calendar
    url: https://calendar.fourthestate.org/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.fourthestate.org
  baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
